name: artifacts

on: workflow_dispatch

jobs:
  generate-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/upload-artifact@v4
        with:
          name: logs
          path: ./logs.txt
          if-no-files-found: error
          retention-days: 7

  download-artifact:
    runs-on: ubuntu-latest
    needs: generate-artifact
    steps:
      - uses: actions/checkout@v5

      - name: Descargar artifact
        uses: actions/download-artifact@v4
        with:
          name: logs
          path: download

      - name: Listar archivos descargados
        run: ls -a
